name: API CI/CD
on: 
  push:
    branches: 
      - 'developer/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@master
      - name: Tests
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        run: sbt test
      - name: Build artifacts
        run: sbt build
